/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0-51-g2d9b1ad

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: app.xdd
        File Version: 0

        Created:      8/30/2019 11:18:00 AM
        Created By:   Miles Simpson
        Modified:     2/25/2022 11:53:34 AM
        Modified By:  

    Device Info:
        Vendor Name:  Portland State Aerospace Society
        Vendor ID:    0
        Product Name: OreSat C3
        Product ID:   0

        Description:  OreSat C3 Node Object Dictionary
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 50
#define OD_CNT_TPDO 16


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 8
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 32
#define OD_CNT_ARR_1028 8
#define OD_CNT_ARR_1029 6
#define OD_CNT_ARR_1F81 127
#define OD_CNT_ARR_1F82 127
#define OD_CNT_ARR_2020 3
#define OD_CNT_ARR_6005 4


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    char x1008_manufacturerDeviceName[12];
    char x1009_manufacturerHardwareVersion[4];
    char x100A_manufacturerSoftwareVersion[6];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1029_errorBehavior_sub0;
    uint8_t x1029_errorBehavior[OD_CNT_ARR_1029];
} OD_ROM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[OD_CNT_ARR_1003];
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    uint64_t x2010_SCET;
    uint64_t x2011_UTC;
    uint8_t x2020_MCU_UniqueDeviceID_sub0;
    uint32_t x2020_MCU_UniqueDeviceID[OD_CNT_ARR_2020];
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t TS_CAL1;
        uint16_t TS_CAL2;
        uint16_t VREFINT_CAL;
    } x2021_MCU_Calibration;
    struct {
        uint8_t highestSub_indexSupported;
        int8_t temperature;
        uint8_t VREFINT;
        uint8_t VBAT;
        uint8_t VBUSP_Current;
        uint16_t temperatureRaw;
        uint16_t VREFINT_Raw;
        uint16_t VBAT_Raw;
        uint16_t VBUSP_CurrentRaw;
    } x2022_MCU_Sensors;
    uint8_t x2100_errorStatusBits[10];
    char x6000_C3_State[2];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t uptime;
        uint8_t eMMC_Usage;
        int8_t UHF_Temperature;
        uint16_t UHF_FWD_Pwr;
        uint16_t UHF_REV_Pwr;
        uint8_t OPD_Current;
    } x7000_C3_Telemetry;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t VBattBP1;
        uint16_t VBattBP2;
        uint16_t VCellMaxBP1;
        uint16_t VCellMaxBP2;
        uint16_t VCellMinBP1;
        uint16_t VCellMinBP2;
        uint16_t VCellBP1;
        uint16_t VCellBP2;
        uint16_t VCell1_BP1;
        uint16_t VCell1_BP2;
        uint16_t VCell2_BP1;
        uint16_t VCell2_BP2;
        uint16_t VCellAvgBP1;
        uint16_t VCellAvgBP2;
        int16_t currentBP1;
        int16_t currentBP2;
        int16_t currentAvgBP1;
        int16_t currentAvgBP2;
        int16_t currentMaxBP1;
        int16_t currentMaxBP2;
        int16_t currentMinBP1;
        int16_t currentMinBP2;
        uint16_t fullCapacityBP1;
        uint16_t fullCapacityBP2;
        uint16_t reportedCapacityBP1;
        uint16_t reportedCapacityBP2;
        uint16_t timeToEmptyBP1;
        uint16_t timeToEmptyBP2;
        uint16_t timeToFullBP1;
        uint16_t timeToFullBP2;
        uint16_t cyclesBP1;
        uint16_t cyclesBP2;
        uint8_t reportedStateOfChargeBP1;
        uint8_t reportedStateOfChargeBP2;
        int16_t temperatureBP1;
        int16_t temperatureBP2;
        int16_t temperatureAvgBP1;
        int16_t temperatureAvgBP2;
        int16_t temperatureMaxBP1;
        int16_t temperatureMaxBP2;
        int16_t temperatureMinBP1;
        int16_t temperatureMinBP2;
        uint8_t stateBP1;
        uint8_t stateBP2;
    } x7001_battery;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t VBattBP1;
        uint16_t VBattBP2;
        uint16_t VCellMaxBP1;
        uint16_t VCellMaxBP2;
        uint16_t VCellMinBP1;
        uint16_t VCellMinBP2;
        uint16_t VCellBP1;
        uint16_t VCellBP2;
        uint16_t VCell1_BP1;
        uint16_t VCell1_BP2;
        uint16_t VCell2_BP1;
        uint16_t VCell2_BP2;
        uint16_t VCellAvgBP1;
        uint16_t VCellAvgBP2;
        int16_t currentBP1;
        int16_t currentBP2;
        int16_t currentAvgBP1;
        int16_t currentAvgBP2;
        int16_t currentMaxBP1;
        int16_t currentMaxBP2;
        int16_t currentMinBP1;
        int16_t currentMinBP2;
        uint16_t fullCapacityBP1;
        uint16_t fullCapacityBP2;
        uint16_t reportedCapacityBP1;
        uint16_t reportedCapacityBP2;
        uint16_t timeToEmptyBP1;
        uint16_t timeToEmptyBP2;
        uint16_t timeToFullBP1;
        uint16_t timeToFullBP2;
        uint16_t cyclesBP1;
        uint16_t cyclesBP2;
        uint8_t reportedStateOfChargeBP1;
        uint8_t reportedStateOfChargeBP2;
        int16_t temperatureBP1;
        int16_t temperatureBP2;
        int16_t temperatureAvgBP1;
        int16_t temperatureAvgBP2;
        int16_t temperatureMaxBP1;
        int16_t temperatureMaxBP2;
        int16_t temperatureMinBP1;
        int16_t temperatureMinBP2;
        uint8_t stateBP1;
        uint8_t stateBP2;
    } x7002_battery;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7003_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7004_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7005_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7006_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7007_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7008_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x7009_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t voltage;
        int16_t current;
        uint16_t power;
        uint16_t voltageAvg;
        int16_t currentAvg;
        uint16_t powerAvg;
        uint16_t voltageMax;
        int16_t currentMax;
        uint16_t powerMax;
        uint16_t energy;
        int8_t cell_1_Temp;
        int8_t cell_2_Temp;
        int8_t cell_1_TempMin;
        int8_t cell_2_TempMin;
        int8_t cell_1_TempMax;
        int8_t cell_2_TempMax;
    } x700A_solarPanel;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t rootPartitionPercent;
        uint8_t RAM_Percent;
        uint8_t freadCacheLength;
        uint8_t fwriteCacheLength;
        uint8_t activeApps;
        uint8_t failedApps;
        uint8_t updaterStatus;
        uint8_t updatesAvailable;
        int16_t rightAscension;
        int16_t declination;
        int16_t roll;
        uint64_t timestamp;
    } x700B_starTracker;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t rootPartitionPercent;
        uint8_t RAM_Percent;
        uint8_t freadCacheLength;
        uint8_t fwriteCacheLength;
        uint8_t activeApps;
        uint8_t failedApps;
        uint8_t updaterStatus;
        uint8_t updatesAvailable;
        int16_t rightAscension;
        int16_t declination;
        int16_t roll;
        uint64_t timestamp;
    } x700C_starTracker;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t rootPartitionPercent;
        uint8_t RAM_Percent;
        uint8_t freadCacheLength;
        uint8_t fwriteCacheLength;
        uint8_t activeApps;
        uint8_t failedApps;
        uint8_t updaterStatus;
        uint8_t updatesAvailable;
        uint8_t GPS_Status;
        uint8_t satellitesLocked;
        uint64_t timestamp;
        int32_t positionX;
        int32_t positionY;
        int32_t positionZ;
        int32_t velocityX;
        int32_t velocityY;
        int32_t velocityZ;
    } x700D_GPS;
    struct {
        uint8_t highestSub_indexSupported;
        int16_t gyroPitch;
        int16_t gyroYaw;
        int16_t gyroRoll;
        int16_t accelerationX;
        int16_t accelerationY;
        int16_t accelerationZ;
        uint8_t IMUTemp;
        int16_t magnetometerPZ1_X;
        int16_t magnetometerPZ1_Y;
        int16_t magnetometerPZ1_Z;
        int16_t magnetometerPZ2_X;
        int16_t magnetometerPZ2_Y;
        int16_t magnetometerPZ2_Z;
        int16_t magnetometerMZ1_X;
        int16_t magnetometerMZ1_Y;
        int16_t magnetometerMZ1_Z;
        int16_t magnetometerMZ2_X;
        int16_t magnetometerMZ2_Y;
        int16_t magnetometerMZ2_Z;
    } x700E_ACS;
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t subObject_1;
    } x700F_RWB;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t rootPartitionPercent;
        uint8_t RAM_Percent;
        uint8_t freadCacheLength;
        uint8_t fwriteCacheLength;
        uint8_t activeApps;
        uint8_t failedApps;
        uint8_t updaterStatus;
        uint8_t updatesAvailable;
        bool_t transmitting;
    } x7013_dxWiFi;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t rootPartitionPercent;
        uint8_t RAM_Percent;
        uint8_t freadCacheLength;
        uint8_t fwriteCacheLength;
        uint8_t activeApps;
        uint8_t failedApps;
        uint8_t updaterStatus;
        uint8_t updatesAvailable;
        bool_t TEC_Enable;
        bool_t TEC_Saturated;
        uint8_t TEC_Temperature;
        uint32_t TEC_Captures;
    } x7014_CFC;
} OD_RAM_t;

typedef struct {
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    uint8_t x1019_synchronousCounterOverflowValue;
    uint8_t x1028_emergencyConsumerObject_sub0;
    uint32_t x1028_emergencyConsumerObject[OD_CNT_ARR_1028];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
        uint8_t node_IDOfTheSDOClient;
    } x1200_SDOServerParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1404_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1405_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1406_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1407_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1408_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1409_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140A_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140B_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140C_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140D_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140E_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x140F_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1410_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1411_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1412_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1413_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1414_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1415_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1416_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1417_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1418_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1419_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141A_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141B_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141C_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141D_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141E_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x141F_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1420_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1421_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1422_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1423_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1424_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1425_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1426_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1427_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1428_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1429_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142A_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142B_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142C_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142D_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142E_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x142F_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1430_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1431_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1604_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1605_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1606_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1607_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1608_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1609_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160A_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160B_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160C_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160D_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160E_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x160F_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1610_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1611_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1612_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1613_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1614_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1615_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1616_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1617_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1618_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1619_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161A_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161B_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161C_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161D_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161E_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x161F_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1620_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1621_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1622_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1623_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1624_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1625_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1626_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1627_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1628_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1629_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162A_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162B_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162C_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162D_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162E_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x162F_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1630_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1631_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1804_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1805_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1806_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1807_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1808_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1809_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180A_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180B_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180C_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180D_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180E_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x180F_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A03_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A04_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A05_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A06_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A07_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A08_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A09_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0A_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0B_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0C_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0D_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0E_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject_1;
        uint32_t applicationObject_2;
        uint32_t applicationObject_3;
        uint32_t applicationObject_4;
        uint32_t applicationObject_5;
        uint32_t applicationObject_6;
        uint32_t applicationObject_7;
        uint32_t applicationObject_8;
    } x1A0F_TPDOMappingParameter;
    uint32_t x1F80_NMTStartup;
    uint8_t x1F81_slaveAssignment_sub0;
    uint8_t x1F82_requestNMT_sub0;
} OD_PERSIST_COMM_t;

typedef struct {
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t bdefault;
        uint8_t ttoggle;
        uint8_t ntoggle;
        uint8_t ctoggle;
    } x2000_BUS_Management;
} OD_PERSIST_MFR_t;

typedef struct {
    struct {
        uint8_t highestSub_indexSupported;
        uint16_t saveInterval;
        uint16_t EDL_Timeout;
        uint16_t resetTimeout;
        bool_t factoryReset;
    } x6001_stateControl;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t timeout;
        uint32_t actuationTime;
        uint8_t attempts;
    } x6002_deploymentControl;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t timeout;
        uint32_t beaconInterval;
    } x6003_TX_Control;
} OD_PERSIST_APP_t;

typedef struct {
    struct {
        uint8_t highestSub_indexSupported;
        uint64_t timestamp;
        uint32_t alarmA;
        uint32_t alarmB;
        uint32_t wakeup;
        uint32_t lastTX_Enable;
        uint32_t lastEDL;
        bool_t deployed;
        uint16_t powerCycles;
        uint32_t LBandRX_Bytes;
        uint32_t LBandRX_Packets;
        uint32_t UHF_RX_Bytes;
        uint32_t UHF_RX_Packets;
        uint64_t VC1_SequenceCount;
        uint64_t VC1_ExpediteCount;
        uint32_t EDL_SequenceCount;
        uint32_t EDL_RejectedCount;
    } x6004_persistentState;
} OD_PERSIST_STATE_t;

typedef struct {
    uint8_t x6005_cryptoKeys_sub0;
    uint8_t x6005_cryptoKeys[OD_CNT_ARR_6005][32];
} OD_PERSIST_KEYS_t;

#ifndef OD_ATTR_ROM
#define OD_ATTR_ROM
#endif
extern OD_ATTR_ROM OD_ROM_t OD_ROM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_PERSIST_MFR
#define OD_ATTR_PERSIST_MFR
#endif
extern OD_ATTR_PERSIST_MFR OD_PERSIST_MFR_t OD_PERSIST_MFR;

#ifndef OD_ATTR_PERSIST_APP
#define OD_ATTR_PERSIST_APP
#endif
extern OD_ATTR_PERSIST_APP OD_PERSIST_APP_t OD_PERSIST_APP;

#ifndef OD_ATTR_PERSIST_STATE
#define OD_ATTR_PERSIST_STATE
#endif
extern OD_ATTR_PERSIST_STATE OD_PERSIST_STATE_t OD_PERSIST_STATE;

#ifndef OD_ATTR_PERSIST_KEYS
#define OD_ATTR_PERSIST_KEYS
#endif
extern OD_ATTR_PERSIST_KEYS OD_PERSIST_KEYS_t OD_PERSIST_KEYS;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1002 &OD->list[2]
#define OD_ENTRY_H1003 &OD->list[3]
#define OD_ENTRY_H1005 &OD->list[4]
#define OD_ENTRY_H1006 &OD->list[5]
#define OD_ENTRY_H1007 &OD->list[6]
#define OD_ENTRY_H1008 &OD->list[7]
#define OD_ENTRY_H1009 &OD->list[8]
#define OD_ENTRY_H100A &OD->list[9]
#define OD_ENTRY_H1010 &OD->list[10]
#define OD_ENTRY_H1011 &OD->list[11]
#define OD_ENTRY_H1014 &OD->list[12]
#define OD_ENTRY_H1015 &OD->list[13]
#define OD_ENTRY_H1016 &OD->list[14]
#define OD_ENTRY_H1017 &OD->list[15]
#define OD_ENTRY_H1018 &OD->list[16]
#define OD_ENTRY_H1019 &OD->list[17]
#define OD_ENTRY_H1028 &OD->list[18]
#define OD_ENTRY_H1029 &OD->list[19]
#define OD_ENTRY_H1200 &OD->list[20]
#define OD_ENTRY_H1280 &OD->list[21]
#define OD_ENTRY_H1400 &OD->list[22]
#define OD_ENTRY_H1401 &OD->list[23]
#define OD_ENTRY_H1402 &OD->list[24]
#define OD_ENTRY_H1403 &OD->list[25]
#define OD_ENTRY_H1404 &OD->list[26]
#define OD_ENTRY_H1405 &OD->list[27]
#define OD_ENTRY_H1406 &OD->list[28]
#define OD_ENTRY_H1407 &OD->list[29]
#define OD_ENTRY_H1408 &OD->list[30]
#define OD_ENTRY_H1409 &OD->list[31]
#define OD_ENTRY_H140A &OD->list[32]
#define OD_ENTRY_H140B &OD->list[33]
#define OD_ENTRY_H140C &OD->list[34]
#define OD_ENTRY_H140D &OD->list[35]
#define OD_ENTRY_H140E &OD->list[36]
#define OD_ENTRY_H140F &OD->list[37]
#define OD_ENTRY_H1410 &OD->list[38]
#define OD_ENTRY_H1411 &OD->list[39]
#define OD_ENTRY_H1412 &OD->list[40]
#define OD_ENTRY_H1413 &OD->list[41]
#define OD_ENTRY_H1414 &OD->list[42]
#define OD_ENTRY_H1415 &OD->list[43]
#define OD_ENTRY_H1416 &OD->list[44]
#define OD_ENTRY_H1417 &OD->list[45]
#define OD_ENTRY_H1418 &OD->list[46]
#define OD_ENTRY_H1419 &OD->list[47]
#define OD_ENTRY_H141A &OD->list[48]
#define OD_ENTRY_H141B &OD->list[49]
#define OD_ENTRY_H141C &OD->list[50]
#define OD_ENTRY_H141D &OD->list[51]
#define OD_ENTRY_H141E &OD->list[52]
#define OD_ENTRY_H141F &OD->list[53]
#define OD_ENTRY_H1420 &OD->list[54]
#define OD_ENTRY_H1421 &OD->list[55]
#define OD_ENTRY_H1422 &OD->list[56]
#define OD_ENTRY_H1423 &OD->list[57]
#define OD_ENTRY_H1424 &OD->list[58]
#define OD_ENTRY_H1425 &OD->list[59]
#define OD_ENTRY_H1426 &OD->list[60]
#define OD_ENTRY_H1427 &OD->list[61]
#define OD_ENTRY_H1428 &OD->list[62]
#define OD_ENTRY_H1429 &OD->list[63]
#define OD_ENTRY_H142A &OD->list[64]
#define OD_ENTRY_H142B &OD->list[65]
#define OD_ENTRY_H142C &OD->list[66]
#define OD_ENTRY_H142D &OD->list[67]
#define OD_ENTRY_H142E &OD->list[68]
#define OD_ENTRY_H142F &OD->list[69]
#define OD_ENTRY_H1430 &OD->list[70]
#define OD_ENTRY_H1431 &OD->list[71]
#define OD_ENTRY_H1600 &OD->list[72]
#define OD_ENTRY_H1601 &OD->list[73]
#define OD_ENTRY_H1602 &OD->list[74]
#define OD_ENTRY_H1603 &OD->list[75]
#define OD_ENTRY_H1604 &OD->list[76]
#define OD_ENTRY_H1605 &OD->list[77]
#define OD_ENTRY_H1606 &OD->list[78]
#define OD_ENTRY_H1607 &OD->list[79]
#define OD_ENTRY_H1608 &OD->list[80]
#define OD_ENTRY_H1609 &OD->list[81]
#define OD_ENTRY_H160A &OD->list[82]
#define OD_ENTRY_H160B &OD->list[83]
#define OD_ENTRY_H160C &OD->list[84]
#define OD_ENTRY_H160D &OD->list[85]
#define OD_ENTRY_H160E &OD->list[86]
#define OD_ENTRY_H160F &OD->list[87]
#define OD_ENTRY_H1610 &OD->list[88]
#define OD_ENTRY_H1611 &OD->list[89]
#define OD_ENTRY_H1612 &OD->list[90]
#define OD_ENTRY_H1613 &OD->list[91]
#define OD_ENTRY_H1614 &OD->list[92]
#define OD_ENTRY_H1615 &OD->list[93]
#define OD_ENTRY_H1616 &OD->list[94]
#define OD_ENTRY_H1617 &OD->list[95]
#define OD_ENTRY_H1618 &OD->list[96]
#define OD_ENTRY_H1619 &OD->list[97]
#define OD_ENTRY_H161A &OD->list[98]
#define OD_ENTRY_H161B &OD->list[99]
#define OD_ENTRY_H161C &OD->list[100]
#define OD_ENTRY_H161D &OD->list[101]
#define OD_ENTRY_H161E &OD->list[102]
#define OD_ENTRY_H161F &OD->list[103]
#define OD_ENTRY_H1620 &OD->list[104]
#define OD_ENTRY_H1621 &OD->list[105]
#define OD_ENTRY_H1622 &OD->list[106]
#define OD_ENTRY_H1623 &OD->list[107]
#define OD_ENTRY_H1624 &OD->list[108]
#define OD_ENTRY_H1625 &OD->list[109]
#define OD_ENTRY_H1626 &OD->list[110]
#define OD_ENTRY_H1627 &OD->list[111]
#define OD_ENTRY_H1628 &OD->list[112]
#define OD_ENTRY_H1629 &OD->list[113]
#define OD_ENTRY_H162A &OD->list[114]
#define OD_ENTRY_H162B &OD->list[115]
#define OD_ENTRY_H162C &OD->list[116]
#define OD_ENTRY_H162D &OD->list[117]
#define OD_ENTRY_H162E &OD->list[118]
#define OD_ENTRY_H162F &OD->list[119]
#define OD_ENTRY_H1630 &OD->list[120]
#define OD_ENTRY_H1631 &OD->list[121]
#define OD_ENTRY_H1800 &OD->list[122]
#define OD_ENTRY_H1801 &OD->list[123]
#define OD_ENTRY_H1802 &OD->list[124]
#define OD_ENTRY_H1803 &OD->list[125]
#define OD_ENTRY_H1804 &OD->list[126]
#define OD_ENTRY_H1805 &OD->list[127]
#define OD_ENTRY_H1806 &OD->list[128]
#define OD_ENTRY_H1807 &OD->list[129]
#define OD_ENTRY_H1808 &OD->list[130]
#define OD_ENTRY_H1809 &OD->list[131]
#define OD_ENTRY_H180A &OD->list[132]
#define OD_ENTRY_H180B &OD->list[133]
#define OD_ENTRY_H180C &OD->list[134]
#define OD_ENTRY_H180D &OD->list[135]
#define OD_ENTRY_H180E &OD->list[136]
#define OD_ENTRY_H180F &OD->list[137]
#define OD_ENTRY_H1A00 &OD->list[138]
#define OD_ENTRY_H1A01 &OD->list[139]
#define OD_ENTRY_H1A02 &OD->list[140]
#define OD_ENTRY_H1A03 &OD->list[141]
#define OD_ENTRY_H1A04 &OD->list[142]
#define OD_ENTRY_H1A05 &OD->list[143]
#define OD_ENTRY_H1A06 &OD->list[144]
#define OD_ENTRY_H1A07 &OD->list[145]
#define OD_ENTRY_H1A08 &OD->list[146]
#define OD_ENTRY_H1A09 &OD->list[147]
#define OD_ENTRY_H1A0A &OD->list[148]
#define OD_ENTRY_H1A0B &OD->list[149]
#define OD_ENTRY_H1A0C &OD->list[150]
#define OD_ENTRY_H1A0D &OD->list[151]
#define OD_ENTRY_H1A0E &OD->list[152]
#define OD_ENTRY_H1A0F &OD->list[153]
#define OD_ENTRY_H1F80 &OD->list[154]
#define OD_ENTRY_H1F81 &OD->list[155]
#define OD_ENTRY_H1F82 &OD->list[156]
#define OD_ENTRY_H1F89 &OD->list[157]
#define OD_ENTRY_H2000 &OD->list[158]
#define OD_ENTRY_H2010 &OD->list[159]
#define OD_ENTRY_H2011 &OD->list[160]
#define OD_ENTRY_H2020 &OD->list[161]
#define OD_ENTRY_H2021 &OD->list[162]
#define OD_ENTRY_H2022 &OD->list[163]
#define OD_ENTRY_H2100 &OD->list[164]
#define OD_ENTRY_H6000 &OD->list[165]
#define OD_ENTRY_H6001 &OD->list[166]
#define OD_ENTRY_H6002 &OD->list[167]
#define OD_ENTRY_H6003 &OD->list[168]
#define OD_ENTRY_H6004 &OD->list[169]
#define OD_ENTRY_H6005 &OD->list[170]
#define OD_ENTRY_H7000 &OD->list[171]
#define OD_ENTRY_H7001 &OD->list[172]
#define OD_ENTRY_H7002 &OD->list[173]
#define OD_ENTRY_H7003 &OD->list[174]
#define OD_ENTRY_H7004 &OD->list[175]
#define OD_ENTRY_H7005 &OD->list[176]
#define OD_ENTRY_H7006 &OD->list[177]
#define OD_ENTRY_H7007 &OD->list[178]
#define OD_ENTRY_H7008 &OD->list[179]
#define OD_ENTRY_H7009 &OD->list[180]
#define OD_ENTRY_H700A &OD->list[181]
#define OD_ENTRY_H700B &OD->list[182]
#define OD_ENTRY_H700C &OD->list[183]
#define OD_ENTRY_H700D &OD->list[184]
#define OD_ENTRY_H700E &OD->list[185]
#define OD_ENTRY_H700F &OD->list[186]
#define OD_ENTRY_H7013 &OD->list[187]
#define OD_ENTRY_H7014 &OD->list[188]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1002_manufacturerStatusRegister &OD->list[2]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[3]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[4]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[5]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[6]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[7]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[8]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[9]
#define OD_ENTRY_H1010_storeParameters &OD->list[10]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[11]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[12]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[13]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[14]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[15]
#define OD_ENTRY_H1018_identity &OD->list[16]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[17]
#define OD_ENTRY_H1028_emergencyConsumerObject &OD->list[18]
#define OD_ENTRY_H1029_errorBehavior &OD->list[19]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[20]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[21]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1404_RPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1405_RPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1406_RPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1407_RPDOCommunicationParameter &OD->list[29]
#define OD_ENTRY_H1408_RPDOCommunicationParameter &OD->list[30]
#define OD_ENTRY_H1409_RPDOCommunicationParameter &OD->list[31]
#define OD_ENTRY_H140A_RPDOCommunicationParameter &OD->list[32]
#define OD_ENTRY_H140B_RPDOCommunicationParameter &OD->list[33]
#define OD_ENTRY_H140C_RPDOCommunicationParameter &OD->list[34]
#define OD_ENTRY_H140D_RPDOCommunicationParameter &OD->list[35]
#define OD_ENTRY_H140E_RPDOCommunicationParameter &OD->list[36]
#define OD_ENTRY_H140F_RPDOCommunicationParameter &OD->list[37]
#define OD_ENTRY_H1410_RPDOCommunicationParameter &OD->list[38]
#define OD_ENTRY_H1411_RPDOCommunicationParameter &OD->list[39]
#define OD_ENTRY_H1412_RPDOCommunicationParameter &OD->list[40]
#define OD_ENTRY_H1413_RPDOCommunicationParameter &OD->list[41]
#define OD_ENTRY_H1414_RPDOCommunicationParameter &OD->list[42]
#define OD_ENTRY_H1415_RPDOCommunicationParameter &OD->list[43]
#define OD_ENTRY_H1416_RPDOCommunicationParameter &OD->list[44]
#define OD_ENTRY_H1417_RPDOCommunicationParameter &OD->list[45]
#define OD_ENTRY_H1418_RPDOCommunicationParameter &OD->list[46]
#define OD_ENTRY_H1419_RPDOCommunicationParameter &OD->list[47]
#define OD_ENTRY_H141A_RPDOCommunicationParameter &OD->list[48]
#define OD_ENTRY_H141B_RPDOCommunicationParameter &OD->list[49]
#define OD_ENTRY_H141C_RPDOCommunicationParameter &OD->list[50]
#define OD_ENTRY_H141D_RPDOCommunicationParameter &OD->list[51]
#define OD_ENTRY_H141E_RPDOCommunicationParameter &OD->list[52]
#define OD_ENTRY_H141F_RPDOCommunicationParameter &OD->list[53]
#define OD_ENTRY_H1420_RPDOCommunicationParameter &OD->list[54]
#define OD_ENTRY_H1421_RPDOCommunicationParameter &OD->list[55]
#define OD_ENTRY_H1422_RPDOCommunicationParameter &OD->list[56]
#define OD_ENTRY_H1423_RPDOCommunicationParameter &OD->list[57]
#define OD_ENTRY_H1424_RPDOCommunicationParameter &OD->list[58]
#define OD_ENTRY_H1425_RPDOCommunicationParameter &OD->list[59]
#define OD_ENTRY_H1426_RPDOCommunicationParameter &OD->list[60]
#define OD_ENTRY_H1427_RPDOCommunicationParameter &OD->list[61]
#define OD_ENTRY_H1428_RPDOCommunicationParameter &OD->list[62]
#define OD_ENTRY_H1429_RPDOCommunicationParameter &OD->list[63]
#define OD_ENTRY_H142A_RPDOCommunicationParameter &OD->list[64]
#define OD_ENTRY_H142B_RPDOCommunicationParameter &OD->list[65]
#define OD_ENTRY_H142C_RPDOCommunicationParameter &OD->list[66]
#define OD_ENTRY_H142D_RPDOCommunicationParameter &OD->list[67]
#define OD_ENTRY_H142E_RPDOCommunicationParameter &OD->list[68]
#define OD_ENTRY_H142F_RPDOCommunicationParameter &OD->list[69]
#define OD_ENTRY_H1430_RPDOCommunicationParameter &OD->list[70]
#define OD_ENTRY_H1431_RPDOCommunicationParameter &OD->list[71]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[72]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[73]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[74]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[75]
#define OD_ENTRY_H1604_RPDOMappingParameter &OD->list[76]
#define OD_ENTRY_H1605_RPDOMappingParameter &OD->list[77]
#define OD_ENTRY_H1606_RPDOMappingParameter &OD->list[78]
#define OD_ENTRY_H1607_RPDOMappingParameter &OD->list[79]
#define OD_ENTRY_H1608_RPDOMappingParameter &OD->list[80]
#define OD_ENTRY_H1609_RPDOMappingParameter &OD->list[81]
#define OD_ENTRY_H160A_RPDOMappingParameter &OD->list[82]
#define OD_ENTRY_H160B_RPDOMappingParameter &OD->list[83]
#define OD_ENTRY_H160C_RPDOMappingParameter &OD->list[84]
#define OD_ENTRY_H160D_RPDOMappingParameter &OD->list[85]
#define OD_ENTRY_H160E_RPDOMappingParameter &OD->list[86]
#define OD_ENTRY_H160F_RPDOMappingParameter &OD->list[87]
#define OD_ENTRY_H1610_RPDOMappingParameter &OD->list[88]
#define OD_ENTRY_H1611_RPDOMappingParameter &OD->list[89]
#define OD_ENTRY_H1612_RPDOMappingParameter &OD->list[90]
#define OD_ENTRY_H1613_RPDOMappingParameter &OD->list[91]
#define OD_ENTRY_H1614_RPDOMappingParameter &OD->list[92]
#define OD_ENTRY_H1615_RPDOMappingParameter &OD->list[93]
#define OD_ENTRY_H1616_RPDOMappingParameter &OD->list[94]
#define OD_ENTRY_H1617_RPDOMappingParameter &OD->list[95]
#define OD_ENTRY_H1618_RPDOMappingParameter &OD->list[96]
#define OD_ENTRY_H1619_RPDOMappingParameter &OD->list[97]
#define OD_ENTRY_H161A_RPDOMappingParameter &OD->list[98]
#define OD_ENTRY_H161B_RPDOMappingParameter &OD->list[99]
#define OD_ENTRY_H161C_RPDOMappingParameter &OD->list[100]
#define OD_ENTRY_H161D_RPDOMappingParameter &OD->list[101]
#define OD_ENTRY_H161E_RPDOMappingParameter &OD->list[102]
#define OD_ENTRY_H161F_RPDOMappingParameter &OD->list[103]
#define OD_ENTRY_H1620_RPDOMappingParameter &OD->list[104]
#define OD_ENTRY_H1621_RPDOMappingParameter &OD->list[105]
#define OD_ENTRY_H1622_RPDOMappingParameter &OD->list[106]
#define OD_ENTRY_H1623_RPDOMappingParameter &OD->list[107]
#define OD_ENTRY_H1624_RPDOMappingParameter &OD->list[108]
#define OD_ENTRY_H1625_RPDOMappingParameter &OD->list[109]
#define OD_ENTRY_H1626_RPDOMappingParameter &OD->list[110]
#define OD_ENTRY_H1627_RPDOMappingParameter &OD->list[111]
#define OD_ENTRY_H1628_RPDOMappingParameter &OD->list[112]
#define OD_ENTRY_H1629_RPDOMappingParameter &OD->list[113]
#define OD_ENTRY_H162A_RPDOMappingParameter &OD->list[114]
#define OD_ENTRY_H162B_RPDOMappingParameter &OD->list[115]
#define OD_ENTRY_H162C_RPDOMappingParameter &OD->list[116]
#define OD_ENTRY_H162D_RPDOMappingParameter &OD->list[117]
#define OD_ENTRY_H162E_RPDOMappingParameter &OD->list[118]
#define OD_ENTRY_H162F_RPDOMappingParameter &OD->list[119]
#define OD_ENTRY_H1630_RPDOMappingParameter &OD->list[120]
#define OD_ENTRY_H1631_RPDOMappingParameter &OD->list[121]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[122]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[123]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[124]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[125]
#define OD_ENTRY_H1804_TPDOCommunicationParameter &OD->list[126]
#define OD_ENTRY_H1805_TPDOCommunicationParameter &OD->list[127]
#define OD_ENTRY_H1806_TPDOCommunicationParameter &OD->list[128]
#define OD_ENTRY_H1807_TPDOCommunicationParameter &OD->list[129]
#define OD_ENTRY_H1808_TPDOCommunicationParameter &OD->list[130]
#define OD_ENTRY_H1809_TPDOCommunicationParameter &OD->list[131]
#define OD_ENTRY_H180A_TPDOCommunicationParameter &OD->list[132]
#define OD_ENTRY_H180B_TPDOCommunicationParameter &OD->list[133]
#define OD_ENTRY_H180C_TPDOCommunicationParameter &OD->list[134]
#define OD_ENTRY_H180D_TPDOCommunicationParameter &OD->list[135]
#define OD_ENTRY_H180E_TPDOCommunicationParameter &OD->list[136]
#define OD_ENTRY_H180F_TPDOCommunicationParameter &OD->list[137]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[138]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[139]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[140]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[141]
#define OD_ENTRY_H1A04_TPDOMappingParameter &OD->list[142]
#define OD_ENTRY_H1A05_TPDOMappingParameter &OD->list[143]
#define OD_ENTRY_H1A06_TPDOMappingParameter &OD->list[144]
#define OD_ENTRY_H1A07_TPDOMappingParameter &OD->list[145]
#define OD_ENTRY_H1A08_TPDOMappingParameter &OD->list[146]
#define OD_ENTRY_H1A09_TPDOMappingParameter &OD->list[147]
#define OD_ENTRY_H1A0A_TPDOMappingParameter &OD->list[148]
#define OD_ENTRY_H1A0B_TPDOMappingParameter &OD->list[149]
#define OD_ENTRY_H1A0C_TPDOMappingParameter &OD->list[150]
#define OD_ENTRY_H1A0D_TPDOMappingParameter &OD->list[151]
#define OD_ENTRY_H1A0E_TPDOMappingParameter &OD->list[152]
#define OD_ENTRY_H1A0F_TPDOMappingParameter &OD->list[153]
#define OD_ENTRY_H1F80_NMTStartup &OD->list[154]
#define OD_ENTRY_H1F81_slaveAssignment &OD->list[155]
#define OD_ENTRY_H1F82_requestNMT &OD->list[156]
#define OD_ENTRY_H1F89_bootTime &OD->list[157]
#define OD_ENTRY_H2000_BUS_Management &OD->list[158]
#define OD_ENTRY_H2010_SCET &OD->list[159]
#define OD_ENTRY_H2011_UTC &OD->list[160]
#define OD_ENTRY_H2020_MCU_UniqueDeviceID &OD->list[161]
#define OD_ENTRY_H2021_MCU_Calibration &OD->list[162]
#define OD_ENTRY_H2022_MCU_Sensors &OD->list[163]
#define OD_ENTRY_H2100_errorStatusBits &OD->list[164]
#define OD_ENTRY_H6000_C3_State &OD->list[165]
#define OD_ENTRY_H6001_stateControl &OD->list[166]
#define OD_ENTRY_H6002_deploymentControl &OD->list[167]
#define OD_ENTRY_H6003_TX_Control &OD->list[168]
#define OD_ENTRY_H6004_persistentState &OD->list[169]
#define OD_ENTRY_H6005_cryptoKeys &OD->list[170]
#define OD_ENTRY_H7000_C3_Telemetry &OD->list[171]
#define OD_ENTRY_H7001_battery &OD->list[172]
#define OD_ENTRY_H7002_battery &OD->list[173]
#define OD_ENTRY_H7003_solarPanel &OD->list[174]
#define OD_ENTRY_H7004_solarPanel &OD->list[175]
#define OD_ENTRY_H7005_solarPanel &OD->list[176]
#define OD_ENTRY_H7006_solarPanel &OD->list[177]
#define OD_ENTRY_H7007_solarPanel &OD->list[178]
#define OD_ENTRY_H7008_solarPanel &OD->list[179]
#define OD_ENTRY_H7009_solarPanel &OD->list[180]
#define OD_ENTRY_H700A_solarPanel &OD->list[181]
#define OD_ENTRY_H700B_starTracker &OD->list[182]
#define OD_ENTRY_H700C_starTracker &OD->list[183]
#define OD_ENTRY_H700D_GPS &OD->list[184]
#define OD_ENTRY_H700E_ACS &OD->list[185]
#define OD_ENTRY_H700F_RWB &OD->list[186]
#define OD_ENTRY_H7013_dxWiFi &OD->list[187]
#define OD_ENTRY_H7014_CFC &OD->list[188]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
