manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: oresat
      url-base: https://github.com/oresat
    - name: pete
      url-base: https://github.com/plskeggs
    - name: canopennode
      url-base: https://github.com/CANopenNode
  defaults:
    remote: oresat
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        # below, only import Zephyr modules we need;
        # extend this per app in submanifests: see oresat-template-app
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_nxp
    - name: CANopenNode
      remote: canopennode
      revision: 58012aa
      path: common/lib/canopennode_v4/CANopenNode
    - name: oresat-adcs-app
      revision: main
      path: apps/adcs
      #import: submanifests
    - name: oresat-battery-app
      revision: main
      path: apps/battery
      #import: submanifests
    - name: oresat-solar-app
      revision: main
      path: apps/solar
      #import: submanifests
    - name: oresat-template-app
      revision: main
      path: apps/template
      import: submanifests
    - name: oresat-mcxn947-demo
      remote: pete
      revision: main
      path: apps/mcxn947-demo
    - name: oresat-mcxn947-protocard
      remote: pete
      revision: main
      path: apps/mcxn947-demo/boards/mcxn947_protocard

  self:
    path: common
    #import: submanifests
