manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: oresat
      url-base: https://github.com/oresat
    - name: pete
      url-base: https://github.com/plskeggs
    - name: canopennode
      url-base: https://github.com/CANopenNode
  defaults:
    remote: pete
    #remote: oresat
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_nxp
    - name: CANopenNode
      remote: canopennode
      revision: 58012aa
      path: common/lib/canopennode_v4/CANopenNode
    - name: oresat-configs
      remote: oresat
      revision: v1.0.0
    - name: oresat-app-adcs
      revision: main
      path: apps/adcs
      #import: submanifests
    - name: oresat-app-battery
      revision: main
      path: apps/battery
      #import: submanifests
    - name: oresat-app-solar
      revision: main
      path: apps/solar
      #import: submanifests
    - name: oresat-app-template
      revision: main
      path: apps/template
      import: submanifests

  self:
    path: common
    #import: submanifests
