/* Warning: This file is automatically generated by AX-RadioLAB.
   Manual changes are overwritten! */

#include "../COMMON/easyax5043.h"
#include <libmfradio.h>
#include <libmftypes.h>
#include <libmfcrc.h>

// TX: fcarrier=436.500MHz dev=  2.500kHz br= 10.000kBit/s pwr=-10.0dBm
// RX: fcarrier=436.500MHz bw= 15.000kHz br= 10.000kBit/s

__reentrantb void ax5043_set_registers(void) __reentrant
{
	radio_write8(AX5043_REG_MODULATION,          0x08);
	radio_write8(AX5043_REG_ENCODING,            0x01);
	radio_write8(AX5043_REG_FRAMING,             0x06);
	radio_write8(AX5043_REG_PINFUNCSYSCLK,       0x04);
	radio_write8(AX5043_REG_PINFUNCDCLK,         0x00);
	radio_write8(AX5043_REG_PINFUNCDATA,         0x00);
	radio_write8(AX5043_REG_PINFUNCANTSEL,       0x01);
	radio_write8(AX5043_REG_PINFUNCPWRAMP,       0x07);
	radio_write8(AX5043_REG_WAKEUPXOEARLY,       0x01);
	radio_write8(AX5043_REG_IFFREQ1,             0x03);
	radio_write8(AX5043_REG_IFFREQ0,             0x33);
	radio_write8(AX5043_REG_DECIMATION,          0x0D);
	radio_write8(AX5043_REG_RXDATARATE2,         0x00);
	radio_write8(AX5043_REG_RXDATARATE1,         0x3D);
	radio_write8(AX5043_REG_RXDATARATE0,         0x89);
	radio_write8(AX5043_REG_MAXDROFFSET2,        0x00);
	radio_write8(AX5043_REG_MAXDROFFSET1,        0x00);
	radio_write8(AX5043_REG_MAXDROFFSET0,        0x00);
	radio_write8(AX5043_REG_MAXRFOFFSET2,        0x80);
	radio_write8(AX5043_REG_MAXRFOFFSET1,        0x03);
	radio_write8(AX5043_REG_MAXRFOFFSET0,        0x93);
	radio_write8(AX5043_REG_FSKDMAX1,            0x00);
	radio_write8(AX5043_REG_FSKDMAX0,            0xA6);
	radio_write8(AX5043_REG_FSKDMIN1,            0xFF);
	radio_write8(AX5043_REG_FSKDMIN0,            0x5A);
	radio_write8(AX5043_REG_AMPLFILTER,          0x00);
	radio_write8(AX5043_REG_RXPARAMSETS,         0xF4);
	radio_write8(AX5043_REG_AGCGAIN0,            0xB4);
	radio_write8(AX5043_REG_AGCTARGET0,          0x84);
	radio_write8(AX5043_REG_TIMEGAIN0,           0xF8);
	radio_write8(AX5043_REG_DRGAIN0,             0xF2);
	radio_write8(AX5043_REG_PHASEGAIN0,          0xC3);
	radio_write8(AX5043_REG_FREQUENCYGAINA0,     0x0F);
	radio_write8(AX5043_REG_FREQUENCYGAINB0,     0x1F);
	radio_write8(AX5043_REG_FREQUENCYGAINC0,     0x07);
	radio_write8(AX5043_REG_FREQUENCYGAIND0,     0x07);
	radio_write8(AX5043_REG_AMPLITUDEGAIN0,      0x06);
	radio_write8(AX5043_REG_FREQDEV10,           0x00);
	radio_write8(AX5043_REG_FREQDEV00,           0x00);
	radio_write8(AX5043_REG_BBOFFSRES0,          0x00);
	radio_write8(AX5043_REG_AGCGAIN1,            0xB4);
	radio_write8(AX5043_REG_AGCTARGET1,          0x84);
	radio_write8(AX5043_REG_AGCAHYST1,           0x00);
	radio_write8(AX5043_REG_AGCMINMAX1,          0x00);
	radio_write8(AX5043_REG_TIMEGAIN1,           0xF6);
	radio_write8(AX5043_REG_DRGAIN1,             0xF1);
	radio_write8(AX5043_REG_PHASEGAIN1,          0xC3);
	radio_write8(AX5043_REG_FREQUENCYGAINA1,     0x0F);
	radio_write8(AX5043_REG_FREQUENCYGAINB1,     0x1F);
	radio_write8(AX5043_REG_FREQUENCYGAINC1,     0x07);
	radio_write8(AX5043_REG_FREQUENCYGAIND1,     0x07);
	radio_write8(AX5043_REG_AMPLITUDEGAIN1,      0x06);
	radio_write8(AX5043_REG_FREQDEV11,           0x00);
	radio_write8(AX5043_REG_FREQDEV01,           0x1C);
	radio_write8(AX5043_REG_FOURFSK1,            0x16);
	radio_write8(AX5043_REG_BBOFFSRES1,          0x00);
	radio_write8(AX5043_REG_AGCGAIN3,            0xFF);
	radio_write8(AX5043_REG_AGCTARGET3,          0x84);
	radio_write8(AX5043_REG_AGCAHYST3,           0x00);
	radio_write8(AX5043_REG_AGCMINMAX3,          0x00);
	radio_write8(AX5043_REG_TIMEGAIN3,           0xF5);
	radio_write8(AX5043_REG_DRGAIN3,             0xF0);
	radio_write8(AX5043_REG_PHASEGAIN3,          0xC3);
	radio_write8(AX5043_REG_FREQUENCYGAINA3,     0x0F);
	radio_write8(AX5043_REG_FREQUENCYGAINB3,     0x1F);
	radio_write8(AX5043_REG_FREQUENCYGAINC3,     0x0B);
	radio_write8(AX5043_REG_FREQUENCYGAIND3,     0x0B);
	radio_write8(AX5043_REG_AMPLITUDEGAIN3,      0x06);
	radio_write8(AX5043_REG_FREQDEV13,           0x00);
	radio_write8(AX5043_REG_FREQDEV03,           0x1C);
	radio_write8(AX5043_REG_FOURFSK3,            0x16);
	radio_write8(AX5043_REG_BBOFFSRES3,          0x00);
	radio_write8(AX5043_REG_MODCFGF,             0x02);
	radio_write8(AX5043_REG_FSKDEV2,             0x00);
	radio_write8(AX5043_REG_FSKDEV1,             0x0A);
	radio_write8(AX5043_REG_FSKDEV0,             0x3D);
	radio_write8(AX5043_REG_MODCFGA,             0x05);
	radio_write8(AX5043_REG_TXRATE2,             0x00);
	radio_write8(AX5043_REG_TXRATE1,             0x28);
	radio_write8(AX5043_REG_TXRATE0,             0xF6);
	radio_write8(AX5043_REG_TXPWRCOEFFB1,        0x00);
	radio_write8(AX5043_REG_TXPWRCOEFFB0,        0xAA);
	radio_write8(AX5043_REG_PLLVCOI,             0x98);
	radio_write8(AX5043_REG_PLLRNGCLK,           0x03);
	radio_write8(AX5043_REG_BBTUNE,              0x0F);
	radio_write8(AX5043_REG_BBOFFSCAP,           0x77);
	radio_write8(AX5043_REG_PKTADDRCFG,          0x01);
	radio_write8(AX5043_REG_PKTLENCFG,           0x80);
	radio_write8(AX5043_REG_PKTLENOFFSET,        0x00);
	radio_write8(AX5043_REG_PKTMAXLEN,           0xC8);
	radio_write8(AX5043_REG_MATCH0PAT3,          0xAA);
	radio_write8(AX5043_REG_MATCH0PAT2,          0xCC);
	radio_write8(AX5043_REG_MATCH0PAT1,          0xAA);
	radio_write8(AX5043_REG_MATCH0PAT0,          0xCC);
	radio_write8(AX5043_REG_MATCH0LEN,           0x9F);
	radio_write8(AX5043_REG_MATCH0MAX,           0x1F);
	radio_write8(AX5043_REG_MATCH1PAT1,          0x55);
	radio_write8(AX5043_REG_MATCH1PAT0,          0x55);
	radio_write8(AX5043_REG_MATCH1LEN,           0x8A);
	radio_write8(AX5043_REG_MATCH1MAX,           0x0A);
	radio_write8(AX5043_REG_TMGTXBOOST,          0x32);
	radio_write8(AX5043_REG_TMGTXSETTLE,         0x14);
	radio_write8(AX5043_REG_TMGRXBOOST,          0x32);
	radio_write8(AX5043_REG_TMGRXSETTLE,         0x14);
	radio_write8(AX5043_REG_TMGRXOFFSACQ,        0x00);
	radio_write8(AX5043_REG_TMGRXCOARSEAGC,      0x73);
	radio_write8(AX5043_REG_TMGRXRSSI,           0x03);
	radio_write8(AX5043_REG_TMGRXPREAMBLE2,      0x35);
	radio_write8(AX5043_REG_RSSIABSTHR,          0xE3);
	radio_write8(AX5043_REG_BGNDRSSITHR,         0x00);
	radio_write8(AX5043_REG_PKTCHUNKSIZE,        0x0D);
	radio_write8(AX5043_REG_PKTACCEPTFLAGS,      0x20);
	radio_write8(AX5043_REG_DACVALUE1,           0x00);
	radio_write8(AX5043_REG_DACVALUE0,           0x00);
	radio_write8(AX5043_REG_DACCONFIG,           0x00);
	radio_write8(AX5043_REG_REF,                 0x03);
	radio_write8(AX5043_REG_XTALOSC,             0x04);
	radio_write8(AX5043_REG_XTALAMPL,            0x00);
	radio_write8(AX5043_REG_0xF1C,               0x07);
	radio_write8(AX5043_REG_0xF21,               0x68);
	radio_write8(AX5043_REG_0xF22,               0xFF);
	radio_write8(AX5043_REG_0xF23,               0x84);
	radio_write8(AX5043_REG_0xF26,               0x98);
	radio_write8(AX5043_REG_0xF34,               0x28);
	radio_write8(AX5043_REG_0xF35,               0x10);
	radio_write8(AX5043_REG_0xF44,               0x25);
}


__reentrantb void ax5043_set_registers_tx(void) __reentrant
{
	radio_write8(AX5043_REG_PLLLOOP,             0x09);
	radio_write8(AX5043_REG_PLLCPI,              0x02);
	radio_write8(AX5043_REG_PLLVCODIV,           0x24);
	radio_write8(AX5043_REG_XTALCAP,             0x00);
	radio_write8(AX5043_REG_0xF00,               0x0F);
	radio_write8(AX5043_REG_0xF18,               0x06);
}


__reentrantb void ax5043_set_registers_rx(void) __reentrant
{
	radio_write8(AX5043_REG_PLLLOOP,             0x0B);
	radio_write8(AX5043_REG_PLLCPI,              0x10);
	radio_write8(AX5043_REG_PLLVCODIV,           0x24);
	radio_write8(AX5043_REG_XTALCAP,             0x00);
	radio_write8(AX5043_REG_0xF00,               0x0F);
	radio_write8(AX5043_REG_0xF18,               0x02);
}


__reentrantb void ax5043_set_registers_rxwor(void) __reentrant
{
	radio_write8(AX5043_REG_TMGRXAGC,                 0x06);
	radio_write8(AX5043_REG_TMGRXPREAMBLE1,           0x19);
	radio_write8(AX5043_REG_PKTMISCFLAGS,             0x03);
}


__reentrantb void ax5043_set_registers_rxcont(void) __reentrant
{
	radio_write8(AX5043_REG_TMGRXAGC,                 0x00);
	radio_write8(AX5043_REG_TMGRXPREAMBLE1,           0x00);
	radio_write8(AX5043_REG_PKTMISCFLAGS,             0x00);
}


__reentrantb void ax5043_set_registers_rxcont_singleparamset(void) __reentrant
{
	radio_write8(AX5043_REG_RXPARAMSETS,              0xFF);
	radio_write8(AX5043_REG_FREQDEV13,                0x00);
	radio_write8(AX5043_REG_FREQDEV03,                0x00);
	radio_write8(AX5043_REG_AGCGAIN3,                 0xD6);
}



__reentrantb void axradio_setup_pincfg1(void) __reentrant
{
#if defined __ARMEL__ || defined __ARMEB__

#else
	PALTRADIO = 0x00; //pass through  
#endif

}

__reentrantb void axradio_setup_pincfg2(void) __reentrant
{
#if defined __ARMEL__ || defined __ARMEB__

#else
	PORTR = (PORTR & 0x3F) | 0xc0; //AX8052F100 --> pull-ups on PR6, PR7
#endif

}



#if defined SDCC

#define CONST #

#define CONSTMULFIX24(x)			\
	__asm					\
	mov	r0,dpl				\
	mov	r1,dph				\
	mov	r2,b				\
	mov	r3,a				\
	push	acc				\
	jnb	acc.7,00000$			\
	clr	c				\
	clr	a				\
	subb	a,r0				\
	mov	r0,a				\
	clr	a				\
	subb	a,r1				\
	mov	r1,a				\
	clr	a				\
	subb	a,r2				\
	mov	r2,a				\
	clr	a				\
	subb	a,r3				\
	mov	r3,a				\
00000$:	clr	a				\
	mov	r4,a				\
	mov	r5,a				\
	mov	r6,a				\
	mov	r7,a				\
	;; stage -1				\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r0				\
	mul	ab				\
	mov	r7,a				\
	mov	r4,b				\
	.endif					\
	.if	(((x)>>8)&0xff)			\
	mov	a,CONST (((x)>>8)&0xff)		\
	mov	b,r1				\
	mul	ab				\
	.if	(((x)>>16)&0xff)		\
	add	a,r7				\
	mov	r7,a				\
	mov	a,b				\
	addc	a,r4				\
	mov	r4,a				\
	clr	a				\
	addc	a,r5				\
	mov	r5,a				\
	.else					\
	mov	r7,a				\
	mov	r4,b				\
	.endif					\
	.endif					\
	.if	((x)&0xff)			\
	mov	a,CONST ((x)&0xff)		\
	mov	b,r2				\
	mul	ab				\
	.if	(((x)>>8)&0xffff)		\
	add	a,r7				\
	mov	r7,a				\
	mov	a,b				\
	addc	a,r4				\
	mov	r4,a				\
	clr	a				\
	addc	a,r5				\
	mov	r5,a				\
	.else					\
	mov	r7,a				\
	mov	r4,b				\
	.endif					\
	.endif					\
	;; clear precision extension		\
	clr	a				\
	mov	r7,a				\
	;; stage 0				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r0				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r1				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	.if	(((x)>>8)&0xff)			\
	mov	a,CONST (((x)>>8)&0xff)		\
	mov	b,r2				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	.if	((x)&0xff)			\
	mov	a,CONST ((x)&0xff)		\
	mov	b,r3				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	;; stage 1				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r1				\
	mul	ab				\
	add	a,r5				\
	mov	r5,a				\
	mov	a,b				\
	addc	a,r6				\
	mov	r6,a				\
	clr	a				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r2				\
	mul	ab				\
	add	a,r5				\
	mov	r5,a				\
	mov	a,b				\
	addc	a,r6				\
	mov	r6,a				\
	clr	a				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	.if	(((x)>>8)&0xff)			\
	mov	a,CONST (((x)>>8)&0xff)		\
	mov	b,r3				\
	mul	ab				\
	add	a,r5				\
	mov	r5,a				\
	mov	a,b				\
	addc	a,r6				\
	mov	r6,a				\
	clr	a				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	;; stage 2				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r2				\
	mul	ab				\
	add	a,r6				\
	mov	r6,a				\
	mov	a,b				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r3				\
	mul	ab				\
	add	a,r6				\
	mov	r6,a				\
	mov	a,b				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	;; stage 3				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r3				\
	mul	ab				\
	add	a,r7				\
	mov	r7,a				\
	.endif					\
	pop	acc				\
	jnb	acc.7,00001$			\
	clr	c				\
	clr	a				\
	subb	a,r4				\
	mov	dpl,a				\
	clr	a				\
	subb	a,r5				\
	mov	dph,a				\
	clr	a				\
	subb	a,r6				\
	mov	b,a				\
	clr	a				\
	subb	a,r7				\
	sjmp	00002$				\
00001$:	mov	dpl,r4				\
	mov	dph,r5				\
	mov	b,r6				\
	mov	a,r7				\
00002$:						\
	__endasm

#define CONSTMULFIX16(x)			\
	__asm					\
	mov	r0,dpl				\
	mov	a,dph				\
	mov	r1,a				\
	push	acc				\
	jnb	acc.7,00000$			\
	clr	c				\
	clr	a				\
	subb	a,r0				\
	mov	r0,a				\
	clr	a				\
	subb	a,r1				\
	mov	r1,a				\
00000$:	clr	a				\
	mov	r4,a				\
	mov	r5,a				\
	mov	r6,a				\
	mov	r7,a				\
	;; stage -1				\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r0				\
	mul	ab				\
	mov	r7,a				\
	mov	r4,b				\
	.endif					\
	.if	(((x)>>8)&0xff)			\
	mov	a,CONST (((x)>>8)&0xff)		\
	mov	b,r1				\
	mul	ab				\
	.if	(((x)>>16)&0xff)		\
	add	a,r7				\
	mov	r7,a				\
	mov	a,b				\
	addc	a,r4				\
	mov	r4,a				\
	clr	a				\
	addc	a,r5				\
	mov	r5,a				\
	.else					\
	mov	r7,a				\
	mov	r4,b				\
	.endif					\
	.endif					\
	;; clear precision extension		\
	clr	a				\
	mov	r7,a				\
	;; stage 0				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r0				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	.if	(((x)>>16)&0xff)		\
	mov	a,CONST (((x)>>16)&0xff)	\
	mov	b,r1				\
	mul	ab				\
	add	a,r4				\
	mov	r4,a				\
	mov	a,b				\
	addc	a,r5				\
	mov	r5,a				\
	clr	a				\
	addc	a,r6				\
	mov	r6,a				\
	.endif					\
	;; stage 1				\
	.if	(((x)>>24)&0xff)		\
	mov	a,CONST (((x)>>24)&0xff)	\
	mov	b,r1				\
	mul	ab				\
	add	a,r5				\
	mov	r5,a				\
	mov	a,b				\
	addc	a,r6				\
	mov	r6,a				\
	clr	a				\
	addc	a,r7				\
	mov	r7,a				\
	.endif					\
	pop	acc				\
	jnb	acc.7,00001$			\
	clr	c				\
	clr	a				\
	subb	a,r4				\
	mov	dpl,a				\
	clr	a				\
	subb	a,r5				\
	mov	dph,a				\
	clr	a				\
	subb	a,r6				\
	mov	b,a				\
	clr	a				\
	subb	a,r7				\
	sjmp	00002$				\
00001$:	mov	dpl,r4				\
	mov	dph,r5				\
	mov	b,r6				\
	mov	a,r7				\
00002$:						\
	__endasm

#else // SDCC

#define MUL8_16(x,y) ((uint8_t)((x)&0xff)*(uint16_t)(uint8_t)((y)&0xff))

#define CONSTMULFIX24(x)					\
	if (f >= 0) {						\
		uint32_t r = MUL8_16((x)>>16,f);		\
		r += MUL8_16((x)>>8,f>>8);			\
		r += MUL8_16((x),f>>16);			\
		r >>= 8;					\
		r += MUL8_16((x)>>24,f);			\
		r += MUL8_16((x)>>16,f>>8);			\
		r += MUL8_16((x)>>8,f>>16);			\
		r += MUL8_16((x),f>>24);			\
		r += ((uint32_t)MUL8_16((x)>>24,f>>8))<<8;	\
		r += ((uint32_t)MUL8_16((x)>>16,f>>16))<<8;	\
		r += ((uint32_t)MUL8_16((x)>>8,f>>24))<<8;	\
		r += ((uint32_t)MUL8_16((x)>>24,f>>16))<<16;	\
		r += ((uint32_t)MUL8_16((x)>>16,f>>24))<<16;	\
		r += ((uint32_t)MUL8_16((x)>>24,f>>24))<<24;	\
		return r;					\
	}							\
	{							\
		int32_t r;					\
		f = -f;						\
		r = -(uint32_t)MUL8_16((x)>>16,f);		\
		r -= (uint32_t)MUL8_16((x)>>8,f>>8);		\
		r -= (uint32_t)MUL8_16((x),f>>16);		\
		r >>= 8;					\
		r -= (uint32_t)MUL8_16((x)>>24,f);		\
		r -= (uint32_t)MUL8_16((x)>>16,f>>8);		\
		r -= (uint32_t)MUL8_16((x)>>8,f>>16);		\
		r -= (uint32_t)MUL8_16((x),f>>24);		\
		r -= ((uint32_t)MUL8_16((x)>>24,f>>8))<<8;	\
		r -= ((uint32_t)MUL8_16((x)>>16,f>>16))<<8;	\
		r -= ((uint32_t)MUL8_16((x)>>8,f>>24))<<8;	\
		r -= ((uint32_t)MUL8_16((x)>>24,f>>16))<<16;	\
		r -= ((uint32_t)MUL8_16((x)>>16,f>>24))<<16;	\
		r -= ((uint32_t)MUL8_16((x)>>24,f>>24))<<24;	\
		return r;					\
	}

#define CONSTMULFIX16(x)					\
	if (f >= 0) {						\
		uint32_t r = MUL8_16((x)>>16,f);		\
		r += MUL8_16((x)>>8,f>>8);			\
		r >>= 8;					\
		r += MUL8_16((x)>>24,f);			\
		r += MUL8_16((x)>>16,f>>8);			\
		r += ((uint32_t)MUL8_16((x)>>24,f>>8))<<8;	\
		return r;					\
	}							\
	{							\
		int32_t r;					\
		f = -f;						\
		r = -(uint32_t)MUL8_16((x)>>16,f);		\
		r -= (uint32_t)MUL8_16((x)>>8,f>>8);		\
		r >>= 8;					\
		r -= (uint32_t)MUL8_16((x)>>24,f);		\
		r -= (uint32_t)MUL8_16((x)>>16,f>>8);		\
		r -= ((uint32_t)MUL8_16((x)>>24,f>>8))<<8;	\
		return r;					\
	}

#endif // SDCC

#if defined SDCC
// do not mark as reentrant, otherwise the register allocator will generate suboptimal code
#pragma nooverlay
int32_t axradio_conv_freq_fromhz(int32_t f)
#else
__reentrantb int32_t axradio_conv_freq_fromhz(int32_t f) __reentrant
#endif
{
	/* scale by 1.048576 (true 1.048576) */
	CONSTMULFIX24(0x10c6f7a);
}

#if defined SDCC
// do not mark as reentrant, otherwise the register allocator will generate suboptimal code
#pragma nooverlay
int32_t axradio_conv_freq_tohz(int32_t f)
#else
__reentrantb int32_t axradio_conv_freq_tohz(int32_t f) __reentrant
#endif
{
	/* scale by 0.953674 (true 0.953674) */
	CONSTMULFIX24(0xf42400);
}

const uint8_t __code axradio_phy_innerfreqloop = 0;

#if defined SDCC
// do not mark as reentrant, otherwise the register allocator will generate suboptimal code
#pragma nooverlay
int32_t axradio_conv_freq_fromreg(int32_t f)
#else
__reentrantb int32_t axradio_conv_freq_fromreg(int32_t f) __reentrant
#endif
{
	/* scale by 1.000000 (true 1.000000) */
	CONSTMULFIX16(0x1000000);
}

#if defined SDCC
// do not mark as reentrant, otherwise the register allocator will generate suboptimal code
#pragma nooverlay
int32_t axradio_conv_timeinterval_totimer0(int32_t dt)
#else
__reentrantb int32_t axradio_conv_timeinterval_totimer0(int32_t dt) __reentrant
#endif
{
	/* scale by 0.032776 (true 0.032768) */
	int32_t r;
	dt >>= 5;
	r = dt;
	dt >>= 4;
	r += dt;
	dt >>= 2;
	r -= dt;
	dt >>= 3;
	r += dt;
	return r;
}

__reentrantb uint8_t axradio_byteconv(uint8_t b) __reentrant
{
	return b;
}


__reentrantb void axradio_byteconv_buffer(uint8_t __xdata *buf, uint16_t buflen) __reentrant
{
}

__reentrantb uint16_t axradio_framing_check_crc(uint8_t __xdata *pkt, uint16_t cnt) __reentrant
{
	return cnt;
}

__reentrantb uint16_t axradio_framing_append_crc(uint8_t __xdata *pkt, uint16_t cnt) __reentrant
{
	return cnt;
}





// physical layer
const uint8_t __code axradio_phy_pn9 = 0;
const uint8_t __code axradio_phy_nrchannels = 1;
const uint32_t __code axradio_phy_chanfreq[1] = { 0x1b480001 };
const uint8_t __code axradio_phy_chanpllrnginit[1] = { 0x0a };
const uint8_t __code axradio_phy_chanvcoiinit[1] = { 0x98 };
uint8_t __xdata axradio_phy_chanpllrng[1];
uint8_t __xdata axradio_phy_chanvcoi[1];
const uint8_t __code axradio_phy_vcocalib = 0;
const int32_t __code axradio_phy_maxfreqoffset = 2746;
const int8_t __code axradio_phy_rssioffset = 64;
// axradio_phy_rssioffset is added to AX5043_RSSIREFERENCE and subtracted from chip RSSI value to prevent overflows (8bit RSSI only goes down to -128)
// axradio_phy_rssioffset is also added to AX5043_RSSIABSTHR
const int8_t __code axradio_phy_rssireference = 0xFA + 64;
const int8_t __code axradio_phy_channelbusy = -93 + 64;
const uint16_t __code axradio_phy_cs_period = 7; // timer0 units, 10ms
const uint8_t __code axradio_phy_cs_enabled = 0;
const uint8_t __code axradio_phy_lbt_retries = 0;
const uint8_t __code axradio_phy_lbt_forcetx = 0;
const uint16_t __code axradio_phy_preamble_wor_longlen = 9; // wor_longlen + wor_len totals to 240.0ms plus 32bits
const uint16_t __code axradio_phy_preamble_wor_len = 128;
const uint16_t __code axradio_phy_preamble_longlen = 0;
const uint16_t __code axradio_phy_preamble_len = 32;
const uint8_t __code axradio_phy_preamble_byte = 0xaa;
const uint8_t __code axradio_phy_preamble_flags = 0x38;
const uint8_t __code axradio_phy_preamble_appendbits = 0;
const uint8_t __code axradio_phy_preamble_appendpattern = 0x00;

//framing
const uint8_t __code axradio_framing_maclen = 3;
const uint8_t __code axradio_framing_addrlen = 2;
const uint8_t __code axradio_framing_destaddrpos = 1;
const uint8_t __code axradio_framing_sourceaddrpos = 0xff;
const uint8_t __code axradio_framing_lenpos = 0;
const uint8_t __code axradio_framing_lenoffs = 0;
const uint8_t __code axradio_framing_lenmask = 0xff;
const uint8_t __code axradio_framing_swcrclen = 0;

const uint8_t __code axradio_framing_synclen = 32;
const uint8_t __code axradio_framing_syncword[] = { 0x33, 0x55, 0x33, 0x55};
const uint8_t __code axradio_framing_syncflags = 0x38;
const uint8_t __code axradio_framing_enable_sfdcallback = 0;

const uint32_t __code axradio_framing_ack_timeout = 12; // 16.4ms in wtimer0 units (640Hz)
const uint32_t __code axradio_framing_ack_delay = 313; // 1.0ms in wtimer1 units (20MHz/64)
const uint8_t __code axradio_framing_ack_retransmissions = 0;
const uint8_t __code axradio_framing_ack_seqnrpos = 0xff;

const uint8_t __code axradio_framing_minpayloadlen = 0; // must be set to 1 if the payload directly follows the destination address, and a CRC is configured
//WOR
const uint16_t __code axradio_wor_period = 128;

// synchronous mode
const uint32_t __code axradio_sync_period = 32768; // ACTUALLY FREQ, NOT PERIOD!
const uint32_t __code axradio_sync_xoscstartup = 49;
const uint32_t __code axradio_sync_slave_syncwindow = 98304; // 3.000s
const uint32_t __code axradio_sync_slave_initialsyncwindow = 5898240; //180.000s
const uint32_t __code axradio_sync_slave_syncpause = 19660800; // 600.000s
const int16_t __code axradio_sync_slave_maxperiod = 2020; // in (2^SYNC_K1) * wtimer0 units
const uint8_t __code axradio_sync_slave_resyncloss = 11;  // resyncloss is one more than the number of missed packets to cause a resync
// window 0 is the first window after synchronisation
// window 1 is the window normally used when there are no lost packets
// window 2 is used after one packet is lost, etc
const uint8_t __code axradio_sync_slave_nrrx = 3;
const uint32_t __code axradio_sync_slave_rxadvance[] = { 391, 343, 388 };// 11.926ms, 10.461ms, 11.835ms
const uint32_t __code axradio_sync_slave_rxwindow[] = { 405, 309, 399 }; // 12.354ms, 9.424ms, 12.172ms
const uint32_t __code axradio_sync_slave_rxtimeout = 453; // 13.8ms, maximum duration of a packet
