name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Ubuntu dependencies
      run: |
        sudo apt install autoconf automake gcc-arm-none-eabi libcapstone4 libftdi1-2 libgpiod2 libhidapi-hidraw0 libtool libusb-1.0-0 libusb-1.0-0-dev pkg-config srecord stlink-tools tcl xxd patch

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps eds-utils
        pip install oresat-configs

    - name: Apply C3 patches
      working-directory:
        ext/ChibiOS
      run: |
        patch -p0 < ./../../src/f4/app_control/stm32f42x_43x_efl.patch
        patch -p1 < ./../../src/f4/app_control/stm32f439_hmacsha256.patch

    - name: Compile f0 apps
      run: |
        make -C src/f0/app_battery
        make -C src/f0/app_blinky
        make -C src/f0/app_bootloader
        make -C src/f0/app_devboard
        make -C src/f0/app_imu
        make -C src/f0/app_solar

    - name: Compile f4 apps
      run: |
        make -C src/f4/app_blinky
        make -C src/f4/app_cantest

    - name: Compile l4 apps
      run: |
        make -C src/l4/app_blinky
        make -C src/l4/app_devboard
        make -C src/l4/app_devboard_cpp
